// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzOc1RIQ7m2vjNN65-c_h1pQmd1u03VCI',
    appId: '1:1021820198187:web:3a63c6b0146f11a993b96e',
    messagingSenderId: '1021820198187',
    projectId: 'business-card-maker-80147',
    authDomain: 'business-card-maker-80147.firebaseapp.com',
    storageBucket: 'business-card-maker-80147.appspot.com',
    measurementId: 'G-EDVHQNBZ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJmIiswBd51ZQ_mFd1Mr2yc_1JsI9dhyA',
    appId: '1:1021820198187:android:893763a58244e44393b96e',
    messagingSenderId: '1021820198187',
    projectId: 'business-card-maker-80147',
    storageBucket: 'business-card-maker-80147.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeHXZcLOdifBlrZjXgtfond5qYUooa7MY',
    appId: '1:1021820198187:ios:cd923e24f2e60d8493b96e',
    messagingSenderId: '1021820198187',
    projectId: 'business-card-maker-80147',
    storageBucket: 'business-card-maker-80147.appspot.com',
    iosClientId: '1021820198187-s69d42s0cpknf79o7dq42fctiv2a6apf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mongUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeHXZcLOdifBlrZjXgtfond5qYUooa7MY',
    appId: '1:1021820198187:ios:9da2b7120a42abb593b96e',
    messagingSenderId: '1021820198187',
    projectId: 'business-card-maker-80147',
    storageBucket: 'business-card-maker-80147.appspot.com',
    iosClientId: '1021820198187-mtncc01ph9kp9h1al7gbo4ksqrpjh8kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.mongUi.RunnerTests',
  );
}
